name: Build and Deploy Python App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: python

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: captchasolver-api-h2amghgfbvd3gscd  # ✅ Your Azure Web App name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: python  # ✅ Deploy from /python folder
